Vagrantfile, roles/registrator/defaults/main.yml, roles/weave/tasks/main.yml, vagrant.yml
- This ensures services appear under the correct node in consul
- Fixes another bug where you could not ping a service via its DNS from inside a container (e.g. ping mysql.service.consul)
=> Fix some inconsistencies / bugs with registrator / docker /consul

docs/getting-started-guides/digitalocean.md
extra code escape causing markdown to render badly, also changed a few words to remain consistent across the docs
=> cleanup of markdown for the digitalocean instructions

bootstrap/aws/config-default.sh, bootstrap/aws/util.sh, roles/mesos/defaults/main.yml, roles/mesos/tasks/main.yml
- on aws, the large ephemeral volume is mounted at /mnt by default
- without setting the slave's working dir to /mnt/X, the very small ebs
boot volume will be filled up VERY quickly making the cluster
unoperable.
- bubble up this parameter to the bootstrap/aws scripts
=> [roles/mesos] parameterize slave work_dir

Vagrantfile, docs/packer.md, packer/ubuntu-14.04_amd64-amis.json, packer/ubuntu-14.04_amd64-droplet.json, packer/ubuntu-14.04_amd64-google.json, packer/ubuntu-14.04_amd64.json, vagrant.yml
This should also tackle #160
approach i've taken follows http://semver.org/
>Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Build metadata SHOULD be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85.
=> Fix #159 - Packer box versioning

inventory/aws/inventory, inventory/digitalocean/inventory, site.yml, tests/properties.yml
Sets the weave network to be across the entire cluster and installs docker/registrator on the masters too. This should allow us to launch containers there (which we're probably going to want to do)
=> Deploy docker/weave/registrator to all hosts

Vagrantfile, bootstrap/aws/config-default.sh, bootstrap/aws/util.sh, bootstrap/digitalocean/config-default.sh, bootstrap/digitalocean/util.sh, docs/atlas.md, docs/packer.md, packer/ubuntu-14.04_amd64-amis.json, packer/ubuntu-14.04_amd64-droplet.json, packer/ubuntu-14.04_amd64-google.json, packer/ubuntu-14.04_amd64.json, terraform/aws/bin/ovpn-client-config, terraform/aws/variables.tf, terraform/digitalocean/variables.tf
BIG FAT BREAKING CHANGE.
We need to rebuild all artifacts in correlation with this PR as it changes ```apollo-mesos``` to just ```apollo``` in most of those.
Suggest we keep the artifacts at apollo-mesos in the vagrantcloud and atlas anyway for a bit so we dont break people on 0.1
=> Rename packer / artifacts to just apollo, rather than apollo-mesos

README.md, packer/scripts/common/install_weave.sh
Zettio has removed the project from his user account and set it up under the organisation 'weaveworks'. Pull request to fix the urls and packer script
=> updating weave url since project moved to weaveworks

roles/registrator/defaults/main.yml, roles/registrator/tasks/main.yml
- setting `hostname` is incompatible with `net: host`
- `ansible_all_ipv4_addresses` yields an invalid value for `hostname`
=> [roles/registrator] remove vestigial hostname

roles/docker/handlers/main.yml, roles/marathon/handlers/main.yml, roles/mesos/handlers/main.yml, roles/zookeeper/handlers/main.yml
The shell module as used is not idempotent, use the service module -
built-in idempotency and portable.
=> [roles] use service module for starts/restarts

roles/docker/defaults/main.yml, roles/docker/tasks/main.yml, roles/weave/tasks/main.yml
- this is optional and defaults are only  over-ridden if the following
env vars are defined:
- `APOLLO_docker_graph_dir`
- `APOLLO_docker_tmp_dir`
- needed because for many ec2 instances, the large ephemeral volume is
mounted under /mnt and the boot volume is very small
- rework the lineinfile calls to be idempotent
- rework the lineinfile call in docker and weave so
DOCKER_OPTS directive is accumulative
=> [roles/docker+weave] opt. set graph and tmp dirs

roles/mesos/handlers/main.yml, roles/mesos/tasks/main.yml
Rejigging around how / where mesos gets started / restarted seems to fix #251. Tested on DO.
=> Fix #251 - mesos redirect

Vagrantfile, docs/getting-started-guides/vagrant.md
This plugin actually supports updating the host machines /etc/hosts (the other one only does the guests). This plugin also more supported/used in the community and seems to work better than vagrant-hosts
=> Use vagrant-hostmanager instead of vagrant-hosts plugin

bootstrap/common.sh, terraform/digitalocean/mesos-masters.tf, terraform/digitalocean/mesos-slaves.tf, terraform/digitalocean/variables.tf
In AWS/GCE we do something like - 
```
variable "instance_type" {
default = {
master = "n1-standard-2"
slave  = "n1-standard-2"
}
}
```
however in DO we were using ```instance_size```. This PR just standardises across the board, as we were unable to change the AWS ones.
=> Ensure we use common instance_type instead of _size across the board

examples/drupal-mysql/README.md, examples/drupal-mysql/commerce-kickstart.json, examples/drupal-mysql/drupal7.json, examples/drupal-mysql/drupal8.json
- Improve docs around cloud requirements
- Use marathon groups to launch
- Add drupal7 / drupal 8 JSON files
This fixes #289 
Tested on a c3.large cluster in AWS.
=> Fix #289 & Improve Drupal examples and documentation 

bootstrap/common.sh
This prints a literal `${1}` instead of the value of the first column.
bash refactor commit broke passing APOLLO_* env vars to ansible
5cf39b6a5366d3084c4e113926178f3c7ed34a00
https://github.com/Capgemini/Apollo/blob/5cf39b6a5366d3084c4e113926178f3c7ed34a00/bootstrap/common.sh#L62
=> fix awk error in get_apollo_variables

packer/scripts/ubuntu/install_docker.sh, packer/tests/spec/docker_spec.rb
(context https://github.com/Capgemini/Apollo/issues/315)
- aufs drivers aren't installed by default on Trusty cloud images, which
causes docker to fall back to devicemapper.  This is bad because
devicemapper is completely broken on Trusty
=> [packer] make sure docker is using aufs

roles/weave/templates/weave.conf.j2
Reverting this fix for DO - as it was causing massive CPU & memory spikes in AWS due to weaver taking up a lot of utilisation. The symptom is described over here https://github.com/weaveworks/weave/issues/417
=> Remove -iprange parameter as it is causing weave networking issues in AWS

roles/weave/defaults/main.yml
Addresses issues raised in #342.
Running some tests in aws-public result in much higher stability across the weave network
=> Fix #342 - Weave network instability

examples/drupal-mysql/drupal7.json
Had to remove this comma as marathon was complaining about syntax error when trying to start the Drupal 7 example.
=> Drupal7 Json

Vagrantfile
There was an issue with running chronons on VM. It was because of we didn't pass chronos_zk_url into ansible variables.
=> Added chronos_zk_url variable to ansible.extra_vars

Vagrantfile, Vagrantfile-standalone, ansible-groups.yml, bootstrap/common.sh, bootstrap/vagrant/util.sh, docs/getting-started-guides/vagrant.md, group_vars/vagrant, vagrant-standalone.yml, vagrant.yml
Created a single machine Vagrantfile
=> issue-258 - Create a single machine Vagrantfile

bootstrap/aws/util.sh, bootstrap/common.sh, bootstrap/tests/test.sh, terraform/aws/outputs.tf
This PR removes the `10.` hardcoded value for AWS to provide a dynamic behaviour based on the value of the `aws_vpc.default.cidr_block` variable
=> Providing dynamic ip ranges different than 10.* for AWS based on vpc_cidr_block

vagrant.yml
Currently Chronos fails to start under Marathon because when
slave goes up it has less then 512MB mem free
(at least on OSX Yosemite + VirtualBox 4.3.30 + vagrant 1.7.4)
=> Bump slave mem to 1532MB in vagrant.yml

tests/spec/marathon/marathon_spec.rb
This test is not true anymore as frameworks could be in deployment stage at this time
=> Removing curl deployment in marathon spec.

bootstrap/aws-public/config-default.sh, terraform/aws-public/mesos-masters.tf, terraform/aws-public/mesos-slaves.tf, terraform/aws-public/variables.tf, terraform/aws/mesos-masters.tf, terraform/aws/mesos-slaves.tf, terraform/aws/variables.tf
Changed to a new artifact version with hvm virtualization
=> Changed artifact version

roles/dnsmasq/tasks/main.yml
Dnsmasq container needs set host to network for being able to resolve from inside a container.
This may be due to we are not able to set --cap-add=NET_ADMIN andyshinn/dnsmasq. via ansible until 2.0 get released
=> Dnsmasq container net to host.

terraform/aws-public/variables.tf, terraform/aws/variables.tf
Using docker 1.7.1 while 1.8.0 is not released as 1.7.0 make dnsmasq on docker consistently fail
=> Using amis with docker 1.7.1

roles/mesos/tasks/slave.yml
Docker is now dynamically linked. Dependencies needs to be made available
Tested with docker 1.8.1 so Waiting for https://github.com/Capgemini/Apollo/pull/449/files
=> Libapparmor as a volume for mesos slave container.

roles/serverspec/tasks/main.yml, tests/Gemfile.lock, tests/properties.yml, tests/spec/cadvisor/cadvisor_spec.rb, tests/spec/chronos/chronos_spec.rb, tests/spec/consul/consul_spec.rb, tests/spec/dnsmasq/dnsmasq_spec.rb, tests/spec/marathon/marathon_spec.rb, tests/spec/mesos_master/mesos_master_spec.rb, tests/spec/mesos_slave/mesos_slave_spec.rb, tests/spec/registrator/registrator_spec.rb
Upgrades serverspec, specinfra and temporally comment out should have_volume as it does not work with docker 1.8.1
Probably because changes introduces due to volume drivers from experimental to master
https://github.com/Capgemini/Apollo/issues/463
=> Upgrade serverspecs and temporally comment docker volume tests.

roles/registrator/tasks/main.yml
This allows registrator and the service registry to get back in sync if they fall out of sync
=> Set -resync flag for registrator reregistering all services

roles/weave/defaults/main.yml, roles/weave/tasks/main.yml
weave scope is a massive resource-hog, often taking up constant 20%+ cpu on slaves and masters.
As more containers are launched on the cluster, the scope UI doesn't scale well and the utility of weave scope doesn't justify its cost.  We needed a flag to turn it off.
=> Udacity add weave scope disable flag

roles/haproxy/defaults/main.yml, roles/haproxy/tasks/main.yml, roles/marathon/defaults/main.yml, roles/marathon/tasks/main.yml, roles/registrator/defaults/main.yml, roles/registrator/tasks/main.yml
allows the operator to selectively taint running containers and just run the idempotent bootstrap/apollo-launch.sh, (e.g. changing config files for haproxy, etc)
=> Udacity rebuild container flags

site.yml
- on ubuntu/AWS, this isn't set to a resolvable entity by default
- this causes gethostbyname2 to fail
- gethostbyname2 is used by mesos
=> set the hostname to a resolvable entity

packer/scripts/common/install_weave.sh, packer/ubuntu-14.04_amd64-amis.json, packer/ubuntu-14.04_amd64-droplet.json, packer/ubuntu-14.04_amd64-google.json, packer/ubuntu-14.04_amd64.json, roles/docker/tasks/main.yml, roles/marathon/defaults/main.yml, roles/marathon/tasks/main.yml, roles/mesos/defaults/main.yml, roles/mesos/tasks/slave.yml, roles/registrator/defaults/main.yml, roles/registrator/tasks/main.yml, roles/weave/defaults/main.yml, roles/weave/tasks/main.yml, roles/weave/templates/interfaces.j2, roles/weave/templates/weave.conf.j2, site.yml, terraform/aws-public/variables.tf, terraform/aws/variables.tf, tests/spec/weave/weave_spec.rb
This provides a pretty basic weave 1.2.0 setup so using fastdatapath and respecting the docker0 bridge as the default docker bridge.
**Known issues:**
When running a new service on the cluster Registrator is storing in the first place the docker ip instead of the weave one. If Registrator get restarted it stores the weave ip.
This hopefully will be fixed once this gets it https://github.com/weaveworks/weave/issues/1549
So we can rebuild the images then.
Once docker 1.9 gets released weave/registrator/consul ecosystem will be broken unless this gets support https://github.com/weaveworks/weave/issues/1601
**TODOS:**
To provide Application/environment isolation via weave subnets.
**Future roadmap:**
To investigate and implement a more flexible/pluggable networking system for Apollo once …
=> Weave upgrade 1.2.0, fastadapath and respecting docker0 as default bridge

group_vars/all, roles/cadvisor/meta/main.yml, roles/handlers/handlers/main.yml, roles/weave/tasks/main.yml, site.yml
This set the DOCKER_HOST env variable to be the weave socket at ansible runtime level so containers run by ansible docker module go through weave proxy.
The other possibility is to handle it at the task level an just set the socket as another variable same we are doing for the net, image, state or volumes. Personally I'd be in favour of the second approach so opening this for discussion.
=> DOCKER_HOST to weave socket when running ansible.

roles/docker/tasks/main.yml, terraform/aws-public/variables.tf, terraform/aws/variables.tf
Setting the base images with kernel 3.19
Setting overlay as fs.
Paving the way for overlay network.
=> kernel 3.19 images and overlay fs.

terraform/aws-public/mesos-slaves.tf, terraform/aws/mesos-slaves.tf
At the moment we are attaching the ebs but then is not being mounted so it's not used.
This merge the ebs with the default ami mount root partition where we need more space as only the docker images makes it run out of space.
=> attach ebs to root partition.

roles/docker/tasks/main.yml, roles/docker/templates/config.json.j2, roles/marathon/defaults/main.yml, roles/mesos/templates/mesos-slave.service.j2
This adds simple support for private docker registry if you set some variables (which can be set as external). Comes with a couple of caveats - 
- no support for multiple registries
- not ideal handling of generating the private registry credentials (via just env vars)
I think we can support this better in the future if we have better support overall for securing the platform and do the bootstrap as a multi-step process (e.g. generate security info and then bootstrap the cluster with it in place)
=> Add support for docker private registry

docs/getting-started-guides/aws-public.md, docs/getting-started-guides/aws.md
One thing to note is that there are references to both ```${var.public_key_file}``` (in ```main.tf```) and as well as ```TF_VAR_key_file``` (in ```util.sh```), so both ```TF_VAR_public_key_file``` and ```TF_VAR_key_file``` need to be defined.
It might be better to merge these variables into a single one.
=> Update aws documentation

terraform/aws/private-cloud/main.tf, terraform/aws/public-cloud/main.tf
Allow subnets to be set from environment variables.  This is required to support running in a single availability zone. 
Currently if you try to run in a single az, you get an error with the ELB
Environment variables:
```
export TF_VAR_availability_zones=us-east-1a
```
Error:
```
aws_elb.elb: InvalidConfigurationRequest: ELB cannot be attached to multiple subnets in the same AZ.
```
With this pull request, you can successfully run in a single az by just setting both availability zone and subnets:
```
export TF_VAR_availability_zones=us-east-1a
export TF_VAR_public_subnets=10.0.1.0/24
```
BTW, why would I want to run in a single AZ?  I'm trying to set up Flocker, which only supports a single AZ.  If anyone has gotten this working please send me a message.
=> Support single availability zone on aws
