Capgemini/Apollo

requirements.txt
roles/consul/tasks/main.yml
roles/dnsmasq/tasks/main.yml
roles/docker/tasks/main.yml
roles/marathon/tasks/main.yml
roles/mesos/tasks/main.yml
wercker.yml

opening up so I can test out wercker builds

Change CI tests to do ansible-lint / packer-validate

---

docs/getting-started-guides/aws.md
docs/getting-started-guides/digitalocean.md
docs/getting-started-guides/vagrant.md
roles/consul/defaults/main.yml
roles/consul/handlers/main.yml
roles/consul/tasks/main.yml
roles/consul/templates/consul.json.j2
terraform/digitalocean/mesos-masters.tf
terraform/digitalocean/mesos-slaves.tf
terraform/digitalocean/variables.tf

This attempts to fix some weird inconsistencies around Consul cluster startup failing to elect a cluster leader properly. 
Tested on digitalocean.

Digitalocean atlas version

---

bootstrap/apollo-launch.sh
bootstrap/aws/config-default.sh
bootstrap/aws/util.sh
bootstrap/common.sh
bootstrap/digitalocean/config-default.sh
bootstrap/digitalocean/util.sh
docs/getting-started-guides/aws.md
docs/getting-started-guides/digitalocean.md
terraform/aws/variables.tf
terraform/digitalocean/variables.tf

If we like this I'll add the others clouds in to this pr

152 dynamic vars

---

tests/properties.yml
tests/spec/consul/consul_spec.rb

Made a start on this. 
We need to think about how we are going to split tests for agent/server mode (which have slightly different configs). Any thoughts?

Made a start to #176 - consul specs

---

wercker.yml

This is so we can discuss automated deploy/specs aproach.
Need to set correct artifact name and version.

Automated deployment and specs from wercker

---

docs/getting-started-guides/vagrant.md

Fixed the case on "Apollo" and added a 'sudo' note

---

docs/getting-started-guides/aws.md

Again, not big, but useful for the noob.

Added a note on obtaining the ATLAS_TOKEN

---

site.yml

This fix https://github.com/Capgemini/Apollo/issues/254

Running local task as non sudo.

---

inventory/aws/inventory
inventory/digitalocean/inventory
roles/consul/defaults/main.yml
roles/consul/templates/consul.json.j2

We need to move the population of this group to the dynamic inventory.
See https://github.com/Capgemini/Apollo/issues/218

Creating dc1 group in inventory

---

roles/marathon/handlers/main.yml
roles/marathon/tasks/main.yml
roles/marathon/templates/marathon-wait-for-listen.sh.j2
roles/marathon/templates/marathon.conf.j2
roles/mesos/tasks/main.yml

This issue resurfaced its head again https://github.com/Capgemini/Apollo/issues/167
These combination of changes seem to fix it.

Wait for marathon listen, flush handlers and force a restart to avoid issues with receiving acknowledgement from Mesos

---

README.md
examples/drupal-mysql/README.md
examples/drupal-mysql/drupal-mysql.json
site.yml

Opening up for initial feedback.

Addresses #54 - initial commit add support for deploying drupal on marathon

---

Vagrantfile
roles/consul/defaults/main.yml
roles/consul/templates/consul.json.j2
roles/docker/tasks/main.yml
roles/handlers/handlers/main.yml
roles/haproxy/meta/main.yml
roles/marathon/meta/main.yml
roles/mesos/meta/main.yml
roles/registrator/meta/main.yml
roles/weave/meta/main.yml
roles/zookeeper/meta/main.yml
site.yml

This fixes #278 and also should speed up provisioining because we don't constantly re-run some roles on masters/slaves.

Fix dependencies

---

roles/haproxy/files/haproxy.tmpl
roles/haproxy/tasks/main.yml
terraform/aws-public/elb.tf

- Fix health check for ELB
- Expose health check port on haproxy container
- Use PROXY mode on ELB in AWS
This fix needs more testing

Initial commit on #275 - Fix the ELB

---

terraform/aws/mesos-slaves.tf

porting work from 81bb09905dc2b5cda27e60c5df863a0bbe9dd4a4

fix ELB health checks for non-public aws

---

group_vars/vagrant
roles/haproxy/files/haproxy.tmpl
roles/mesos/tasks/main.yml
roles/zookeeper/tasks/main.yml
roles/zookeeper/templates/zoo.cfg.j2

Correcting styling in ansible files and consule template. I removed the variable "marathon_local_address" which is no longer being used.

Changes variables in ansible roles

---

docs/components/haproxy.md

Fix #123 - document haproxy/consul-template usage

---

docs/getting-started-guides/aws.md

Fixed md guide link from `docs/getting-started-guides/aws.md`

Fixed md guide link

---

packer/scripts/ubuntu/kernel-upgrade.sh
packer/ubuntu-14.04_amd64-amis.json
packer/ubuntu-14.04_amd64-droplet.json
packer/ubuntu-14.04_amd64-google.json
packer/ubuntu-14.04_amd64.json

this upgrades kernel version to make it easier to move to a different storage driver with docker later and gets fixes and performance improvements.

Upgrade kernel

---

packer/ubuntu-14.04_amd64.json

I updated only packer image for vagrant because rest of them didn't required any changes.

Updated packer image for vagrant

---

bootstrap/aws-public/config-default.sh
bootstrap/aws/config-default.sh
packer/scripts/ubuntu/install_docker.sh
packer/tests/spec/docker_spec.rb
packer/ubuntu-14.04_amd64-amis.json
packer/ubuntu-14.04_amd64-droplet.json
packer/ubuntu-14.04_amd64-google.json
packer/ubuntu-14.04_amd64.json
terraform/aws-public/variables.tf
terraform/aws/variables.tf

This is a temporary solving to fix the issue. It is gonna be fixed in the new docker version.

Downgrade docker version from 1.7.1 to 1.7.0

---

docs/getting-started-guides/vagrant.md

Additional info on proxies

---

terraform/aws/bastion-server.tf
terraform/aws/variables.tf

Upgrading docker version on bastion host - issue #505

---

docs/getting-started-guides/vagrant.md

If python 3 used for pip ansible throws an error due to a print statement.

Adding note about python

---

roles/cadvisor/tasks/main.yml
roles/cadvisor/templates/cadvisor-consul.j2
roles/mesos/tasks/master.yml
roles/mesos/tasks/slave.yml
roles/mesos/templates/mesos-exporter-consul.j2
roles/prometheus/tasks/main.yml
roles/prometheus/templates/node-exporter-consul.j2
roles/zookeeper/tasks/main.yml
roles/zookeeper/templates/zookeeper-consul.j2

this could either go in as in or we also need to add -

Initial commit for #580 - add consul health checks based on consul 0.6

---

roles/consul/tasks/main.yml
roles/traefik/defaults/main.yml
roles/traefik/files/wait-for-marathon.sh
roles/traefik/tasks/main.yml
roles/traefik/templates/traefik.service.j2

Add check script for marathon DNS for traefik

---

bootstrap/aws/private-cloud/config-default.sh
bootstrap/aws/public-cloud/config-default.sh

fixes https://github.com/Capgemini/Apollo/issues/615

ansible ssh user is core.

---

roles/marathon/defaults/main.yml
roles/weave/defaults/main.yml

marathon 0.14.1 and weave 1.4.2

upgrade marathon and weave

---

roles/cadvisor/handlers/main.yml
roles/cadvisor/meta/main.yml
roles/cadvisor/tasks/main.yml
roles/consul/handlers/main.yml
roles/consul/tasks/main.yml
roles/marathon/meta/main.yml
roles/marathon/tasks/main.yml
roles/mesos/tasks/master.yml
roles/mesos/tasks/slave.yml
roles/weave/handlers/main.yml
roles/weave/tasks/main.yml
roles/zookeeper/tasks/main.yml

so we dont run into issues provisioning ansible

Do systemd-reloads when service file changes 

---

bootstrap/digitalocean/config-default.sh
terraform/digitalocean/ssh.config

This fixes ansible connection with digitalocean

Use generated id_rsa file for digitalocean ssh access

---

roles/mesos/templates/mesos-slave.service.j2

https://mail-archives.apache.org/mod_mbox/mesos-user/201407.mbox/%3CCAAJX7sjyHypugX8=7iUjwJ84ZUr1uQSNABZL9aq=8Eu8GNQazw@mail.gmail.com%3E

isolate resources in line with systemd and cgroups

---

bootstrap/aws/private-cloud/util.sh
bootstrap/aws/public-cloud/util.sh

This fixes the bug that just crept into master preventing apollo down from working.

Fix apollo down

---

roles/prometheus/defaults/main.yml

Prometheus database url did not match what was in consul, so I updated it.

Fix incorrect DATABASE_URL for prometheus dashboard.

---

terraform/aws/private-cloud/main.tf
terraform/aws/public-cloud/main.tf
terraform/digitalocean/main.tf

https://www.terraform.io/docs/providers/template/r/file.html

use file with template as per docs

---

Vagrantfile-standalone

715 - Changing index from symbol to string.
